name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > mocac.pem
          chmod 600 mocac.pem

      - name: Create ML directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i mocac.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p /home/ec2-user/ml"

      - name: Debug - check ml folder
        run: |
          pwd
          ls -la
          echo "---ml 폴더 내용---"
          ls -la ml/ || echo "ml 폴더 자체가 없음"

      - name: Debug destination string
        run: |
          echo "[${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/ml/]"
    
      - name: Transfer ML files to EC2
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no -i mocac.pem"
        run: |
          HOST="$(echo -n '${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}' | tr -d '[:space:]')"
          rsync -avz ml/ "${HOST}:/home/ec2-user/ml/"

      - name: Restart backend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i mocac.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'

            docker restart redred-backend-notification-service-1

          ENDSSH
